"""'migration'

Revision ID: 918c6436a354
Revises: dedfe8b9aeb0
Create Date: 2019-08-08 20:38:04.529927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918c6436a354'
down_revision = 'dedfe8b9aeb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_song',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('todo', sa.String(length=255), nullable=False),
    sa.Column('regdate', sa.DateTime(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_song')
    # ### end Alembic commands ###
